import { writeFile } from "fs/promises";
import { join } from "path";
import type { NarrationSourceConfig, WordTimestamp } from "../graph";
import { TalkifyProvider } from "../tts/providers/talkify.provider";
import { CustomAudioProvider, type ScriptSegment } from "../tts/providers/custom.provider";

export interface AudioResult {
  audioPath: string;
  timestamps: WordTimestamp[];
}

export async function prepareAudio(
  config: NarrationSourceConfig,
  workDir: string,
  talkifyApiKey?: string,
  scriptSegments: ScriptSegment[] = [],
): Promise<AudioResult> {
  const audioPath = join(workDir, "narration.wav");

  if (config.mode === "precomputed") {
    // Audio pre-generated by audio worker — stored in MinIO as audioKey.
    // CustomAudioProvider downloads it and runs WhisperX for timestamps.
    // Com scriptSegments o WhisperX só alinha o texto conhecido (sem ASR, sem palavras erradas).
    const provider = new CustomAudioProvider();
    const result = await provider.synthesize(undefined, {
      provider: "custom",
      voice: config.audioKey,
      providerConfig: scriptSegments.length > 0 ? { segments: scriptSegments } : undefined,
    });

    await writeFile(audioPath, result.audio);
    return { audioPath, timestamps: result.wordTimestamps };
  }

  if (config.mode === "tts" || config.provider === "talkify") {
    if (!talkifyApiKey) throw new Error("prepareAudio: Talkify API key required");
    if (!config.text) throw new Error("prepareAudio: text required for TTS");

    const provider = new TalkifyProvider(talkifyApiKey);
    const result = await provider.synthesize(config.text, config);

    await writeFile(audioPath, result.audio);
    return { audioPath, timestamps: result.wordTimestamps };
  }

  if (config.provider === "custom") {
    const provider = new CustomAudioProvider();
    const result = await provider.synthesize(undefined, config);
    await writeFile(audioPath, result.audio);
    return { audioPath, timestamps: result.wordTimestamps };
  }

  throw new Error(`prepareAudio: unsupported provider "${config.provider}"`);
}
